[package]
name = "jsonc2json"
version = "0.0.4"
edition = "2021"
include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md"]

[lib]
name = "pyjsonc2json"
crate-type = ["cdylib"]

[dependencies]
json_comments = "0.2.2"
pyo3 = "0.21.1"
